/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.sistemanominas.vista;

import com.sauces.sistemanominas.controlador.Controlador;
import com.sauces.sistemanominas.modelo.Empleado;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoListado = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfIngresos = new javax.swing.JFormattedTextField();
        cbTipo = new javax.swing.JComboBox<>();
        tfSalario = new javax.swing.JFormattedTextField();
        bBorrar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        spHoras = new javax.swing.JSpinner();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        bListar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bDni = new javax.swing.JRadioButton();
        bNombre = new javax.swing.JRadioButton();
        bIngresos = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        menuEmpelado = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miBuscar = new javax.swing.JMenuItem();

        selectorFicheros.setCurrentDirectory(new java.io.File(".")
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de nóminas");
        setResizable(false);

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        jLabel1.setText("DNI");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("TIPO");

        jLabel4.setText("SALARIO");

        jLabel5.setText("INGRESOS");

        tfDni.setEditable(false);

        tfIngresos.setEditable(false);
        tfIngresos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIJO", "EVENTUAL" }));
        cbTipo.setEnabled(false);
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        tfSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        bBorrar.setText("BORRAR");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bModificar.setText("MODIFICAR");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jLabel6.setText("HORAS");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tfIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre)
                            .addComponent(cbTipo, 0, 104, Short.MAX_VALUE)
                            .addComponent(tfSalario)
                            .addComponent(tfDni)
                            .addComponent(spHoras))))
                .addGap(16, 16, 16))
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addComponent(bBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bModificar)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(spHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(tfIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(bModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de empleados"));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        empleadoTM=new EmpleadoTableModel();
        tablaEmpleados.setModel(empleadoTM);
        tablaEmpleados.getSelectionModel().addListSelectionListener(
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent lse){
                    int fila=tablaEmpleados.getSelectedRow();
                    if(fila>=0){
                        mostrarDni(tablaEmpleados.getValueAt(fila,0).toString());
                        mostrarNombre((String)tablaEmpleados.getValueAt(fila, 1));
                        mostrarSalario((float)tablaEmpleados.getValueAt(fila,2));
                        int horas=(int)tablaEmpleados.getValueAt(fila,3);
                        mostrarHoras(horas);
                        if(horas==0){
                            mostrarTipo("FIJO");
                        }else{
                            mostrarTipo("EVENTUAL");
                        }
                        mostrarIngresos((float)tablaEmpleados.getValueAt(fila,4));
                    }
                }
            });
            jScrollPane1.setViewportView(tablaEmpleados);

            bListar.setText("LISTAR EMPLEADOS");
            bListar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bListarActionPerformed(evt);
                }
            });

            jLabel7.setText("ORDEN DEL LISTADO");

            grupoListado.add(bDni);
            bDni.setSelected(true);
            bDni.setText("DNI");

            grupoListado.add(bNombre);
            bNombre.setText("NOMBRE");

            grupoListado.add(bIngresos);
            bIngresos.setText("INGRESOS");

            javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
            panelTabla.setLayout(panelTablaLayout);
            panelTablaLayout.setHorizontalGroup(
                panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTablaLayout.createSequentialGroup()
                    .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTablaLayout.createSequentialGroup()
                            .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTablaLayout.createSequentialGroup()
                                    .addGap(166, 166, 166)
                                    .addComponent(bListar))
                                .addGroup(panelTablaLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bDni)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bIngresos)))
                            .addGap(0, 110, Short.MAX_VALUE))
                        .addGroup(panelTablaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            panelTablaLayout.setVerticalGroup(
                panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTablaLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(bListar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(bDni)
                        .addComponent(bNombre)
                        .addComponent(bIngresos))
                    .addContainerGap(16, Short.MAX_VALUE))
            );

            menuArchivo.setText("Archivo");

            miAbrir.setText("Abrir");
            miAbrir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    miAbrirActionPerformed(evt);
                }
            });
            menuArchivo.add(miAbrir);

            miGuardar.setText("Guardar");
            miGuardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    miGuardarActionPerformed(evt);
                }
            });
            menuArchivo.add(miGuardar);

            jMenuBar1.add(menuArchivo);

            menuEmpelado.setText("Empleado");

            miNuevo.setText("Nuevo");
            miNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    miNuevoActionPerformed(evt);
                }
            });
            menuEmpelado.add(miNuevo);

            miBuscar.setText("Buscar");
            miBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    miBuscarActionPerformed(evt);
                }
            });
            menuEmpelado.add(miBuscar);

            jMenuBar1.add(menuEmpelado);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void miBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarActionPerformed
        // TODO add your handling code here:
         mostrarDni(JOptionPane.showInputDialog("Introduce el DNI del empleado a buscar"));
         controlador.buscarEmpleado();
    }//GEN-LAST:event_miBuscarActionPerformed

    private void miNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoActionPerformed
        // TODO add your handling code here:
        dialogoEmpleado.limpiarCampos();
        if(dialogoEmpleado.mostrar()==DialogoEmpleado.ACEPTAR){
            mostrarDni(dialogoEmpleado.getDni());
            mostrarNombre(dialogoEmpleado.getNombre());
            String tipo=dialogoEmpleado.getTipo();
            mostrarTipo(tipo);
            mostrarSalario(dialogoEmpleado.getSalario());
            if(tipo=="EVENTUAL"){
                mostrarHoras(dialogoEmpleado.getHoras());
            }
            controlador.crearEmpleado();
        }
        
    }//GEN-LAST:event_miNuevoActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
        if(cbTipo.getSelectedItem().equals("FIJO")){
            this.jLabel6.setVisible(false);
            this.spHoras.setVisible(false);
        }else{
            this.jLabel6.setVisible(true);
            this.spHoras.setVisible(true);
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        mostrarDni(JOptionPane.showInputDialog("Introduce el DNI del empleado a despedir"));
       controlador.eliminarEmpleado();
       limpiarCampos();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
        // TODO add your handling code here:
        controlador.listarEmpleados();
    }//GEN-LAST:event_bListarActionPerformed

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        // TODO add your handling code here:
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.cargarEmpleados();
        }
    }//GEN-LAST:event_miAbrirActionPerformed

    private void miGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarActionPerformed
        // TODO add your handling code here:
         if(selectorFicheros.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
        controlador.guardarEmpleados();
         }
    }//GEN-LAST:event_miGuardarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        controlador.modificarEmpleado();
    }//GEN-LAST:event_bModificarActionPerformed
    private Controlador controlador;
    private DialogoEmpleado dialogoEmpleado=new DialogoEmpleado(this,true);
    private EmpleadoTableModel empleadoTM;
    public String getTipo(){
        return (String)cbTipo.getSelectedItem();
    }
    public String getDni(){
        return tfDni.getText();
    }
    public String getNombre(){
        return tfNombre.getText();
    }
    public float getSalario(){
        return Float.parseFloat(this.tfSalario.getText().replace(',','.'));
    }
    public int getHoras(){
        return (int)spHoras.getValue();
    }
    public String getOrden(){
       if(bDni.isSelected()){
           return"DNI";
       }else{
            if(bIngresos.isSelected()){
                return "INGRESOS";
            }else{
                return "NOMBRE";
            }
       }
    }
    public void mostrarTipo(String tipo){
        cbTipo.setSelectedItem(tipo);
    }
    public void mostrarDni(String dni){
        tfDni.setText(dni);
    }
    public void mostrarNombre(String nombre){
        tfNombre.setText(nombre);
    }
    public void mostrarSalario(float salario){
        tfSalario.setValue(salario);
    }
    public void mostrarHoras(int horas){
        spHoras.setValue(horas);
    }
    public String getArchivo(){
        return selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    public void mostrarIngresos(float ingresos){
        tfIngresos.setValue(ingresos);
    }
    public void listarEmpleados(List<Empleado> listado){
        empleadoTM.setListado(listado);
        empleadoTM.fireTableDataChanged();
    }
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    public boolean solicitarConfirmacion(){
       if(JOptionPane.showConfirmDialog(this, "¿Confirmamos?", "Confirmacion", JOptionPane.YES_NO_CANCEL_OPTION)==JOptionPane.YES_OPTION){
           return true;
       }else{
           return false;
       }
    }
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    public void limpiarCampos(){
        tfDni.setText("");
        tfNombre.setText("");
        tfSalario.setValue(0);
        spHoras.setValue(0);
        tfIngresos.setValue(0);
        cbTipo.setSelectedItem("FIJO");
    }
    public void mostrar(){
    setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JRadioButton bDni;
    private javax.swing.JRadioButton bIngresos;
    private javax.swing.JButton bListar;
    private javax.swing.JButton bModificar;
    private javax.swing.JRadioButton bNombre;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.ButtonGroup grupoListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEmpelado;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miBuscar;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miNuevo;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JSpinner spHoras;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField tfDni;
    private javax.swing.JFormattedTextField tfIngresos;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JFormattedTextField tfSalario;
    // End of variables declaration//GEN-END:variables
}
